/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DeveloperSigninRouteImport } from './routes/developer-signin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as MarkerSigninRouteImport } from './routes/marker-signin'
import { Route as MiiRouteImport } from './routes/mii'
import { Route as MiuRouteImport } from './routes/miu'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdvisorRouteImport } from './routes/_authenticated/advisor'
import { Route as AuthenticatedAppealsRouteImport } from './routes/_authenticated/appeals'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeveloperRouteImport } from './routes/_authenticated/developer'
import { Route as AuthenticatedMailRouteImport } from './routes/_authenticated/mail'
import { Route as AuthenticatedMarkerRouteImport } from './routes/_authenticated/marker'
import { Route as AuthenticatedPasswordRouteImport } from './routes/_authenticated/password'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAppealsRouteImport } from './routes/_authenticated/admin.appeals'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin.attendance'
import { Route as AuthenticatedAdminBlocksRouteImport } from './routes/_authenticated/admin.blocks'
import { Route as AuthenticatedAdminClassesRouteImport } from './routes/_authenticated/admin.classes'
import { Route as AuthenticatedAdminCohortsRouteImport } from './routes/_authenticated/admin.cohorts'
import { Route as AuthenticatedAdminDirectoryRouteImport } from './routes/_authenticated/admin.directory'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/admin.feedback'
import { Route as AuthenticatedAdminMarkersRouteImport } from './routes/_authenticated/admin.markers'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedDeveloperIndexRouteImport } from './routes/_authenticated/developer.index'
import { Route as AuthenticatedDeveloperAuditRouteImport } from './routes/_authenticated/developer.audit'
import { Route as AuthenticatedDeveloperEmailRouteImport } from './routes/_authenticated/developer.email'
import { Route as AuthenticatedDeveloperEmergencyRouteImport } from './routes/_authenticated/developer.emergency'
import { Route as AuthenticatedDeveloperFlagsRouteImport } from './routes/_authenticated/developer.flags'
import { Route as AuthenticatedDeveloperHealthRouteImport } from './routes/_authenticated/developer.health'
import { Route as AuthenticatedDeveloperIntegrityRouteImport } from './routes/_authenticated/developer.integrity'
import { Route as AuthenticatedDeveloperPermissionsRouteImport } from './routes/_authenticated/developer.permissions'
import { Route as AuthenticatedDeveloperSearchRouteImport } from './routes/_authenticated/developer.search'
import { Route as AuthenticatedDeveloperSecurityRouteImport } from './routes/_authenticated/developer.security'
import { Route as AuthenticatedDeveloperSupportRouteImport } from './routes/_authenticated/developer.support'
import { Route as AuthenticatedDeveloperToolsRouteImport } from './routes/_authenticated/developer.tools'
import { Route as AuthenticatedDeveloperUsersRouteImport } from './routes/_authenticated/developer.users'
import { Route as AuthenticatedMarkerIndexRouteImport } from './routes/_authenticated/marker.index'
import { Route as AuthenticatedMarkerAppealsRouteImport } from './routes/_authenticated/marker.appeals'
import { Route as AuthenticatedMarkerPasswordRouteImport } from './routes/_authenticated/marker.password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperSigninRoute = DeveloperSigninRouteImport.update({
  id: '/developer-signin',
  path: '/developer-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkerSigninRoute = MarkerSigninRouteImport.update({
  id: '/marker-signin',
  path: '/marker-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MiiRoute = MiiRouteImport.update({
  id: '/mii',
  path: '/mii',
  getParentRoute: () => rootRouteImport,
} as any)
const MiuRoute = MiuRouteImport.update({
  id: '/miu',
  path: '/miu',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdvisorRoute = AuthenticatedAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppealsRoute = AuthenticatedAppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeveloperRoute = AuthenticatedDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMailRoute = AuthenticatedMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarkerRoute = AuthenticatedMarkerRouteImport.update({
  id: '/marker',
  path: '/marker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPasswordRoute = AuthenticatedPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAppealsRoute =
  AuthenticatedAdminAppealsRouteImport.update({
    id: '/appeals',
    path: '/appeals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlocksRoute =
  AuthenticatedAdminBlocksRouteImport.update({
    id: '/blocks',
    path: '/blocks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClassesRoute =
  AuthenticatedAdminClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCohortsRoute =
  AuthenticatedAdminCohortsRouteImport.update({
    id: '/cohorts',
    path: '/cohorts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDirectoryRoute =
  AuthenticatedAdminDirectoryRouteImport.update({
    id: '/directory',
    path: '/directory',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarkersRoute =
  AuthenticatedAdminMarkersRouteImport.update({
    id: '/markers',
    path: '/markers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedDeveloperIndexRoute =
  AuthenticatedDeveloperIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperAuditRoute =
  AuthenticatedDeveloperAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperEmailRoute =
  AuthenticatedDeveloperEmailRouteImport.update({
    id: '/email',
    path: '/email',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperEmergencyRoute =
  AuthenticatedDeveloperEmergencyRouteImport.update({
    id: '/emergency',
    path: '/emergency',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperFlagsRoute =
  AuthenticatedDeveloperFlagsRouteImport.update({
    id: '/flags',
    path: '/flags',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperHealthRoute =
  AuthenticatedDeveloperHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperIntegrityRoute =
  AuthenticatedDeveloperIntegrityRouteImport.update({
    id: '/integrity',
    path: '/integrity',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperPermissionsRoute =
  AuthenticatedDeveloperPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperSearchRoute =
  AuthenticatedDeveloperSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperSecurityRoute =
  AuthenticatedDeveloperSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperSupportRoute =
  AuthenticatedDeveloperSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperToolsRoute =
  AuthenticatedDeveloperToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperUsersRoute =
  AuthenticatedDeveloperUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedMarkerIndexRoute =
  AuthenticatedMarkerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMarkerRoute,
  } as any)
const AuthenticatedMarkerAppealsRoute =
  AuthenticatedMarkerAppealsRouteImport.update({
    id: '/appeals',
    path: '/appeals',
    getParentRoute: () => AuthenticatedMarkerRoute,
  } as any)
const AuthenticatedMarkerPasswordRoute =
  AuthenticatedMarkerPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedMarkerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/developer-signin': typeof DeveloperSigninRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/marker-signin': typeof MarkerSigninRoute
  '/mii': typeof MiiRoute
  '/miu': typeof MiuRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/advisor': typeof AuthenticatedAdvisorRoute
  '/appeals': typeof AuthenticatedAppealsRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer': typeof AuthenticatedDeveloperRouteWithChildren
  '/mail': typeof AuthenticatedMailRoute
  '/marker': typeof AuthenticatedMarkerRouteWithChildren
  '/password': typeof AuthenticatedPasswordRoute
  '/admin/appeals': typeof AuthenticatedAdminAppealsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/blocks': typeof AuthenticatedAdminBlocksRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/cohorts': typeof AuthenticatedAdminCohortsRoute
  '/admin/directory': typeof AuthenticatedAdminDirectoryRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/markers': typeof AuthenticatedAdminMarkersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/developer/audit': typeof AuthenticatedDeveloperAuditRoute
  '/developer/email': typeof AuthenticatedDeveloperEmailRoute
  '/developer/emergency': typeof AuthenticatedDeveloperEmergencyRoute
  '/developer/flags': typeof AuthenticatedDeveloperFlagsRoute
  '/developer/health': typeof AuthenticatedDeveloperHealthRoute
  '/developer/integrity': typeof AuthenticatedDeveloperIntegrityRoute
  '/developer/permissions': typeof AuthenticatedDeveloperPermissionsRoute
  '/developer/search': typeof AuthenticatedDeveloperSearchRoute
  '/developer/security': typeof AuthenticatedDeveloperSecurityRoute
  '/developer/support': typeof AuthenticatedDeveloperSupportRoute
  '/developer/tools': typeof AuthenticatedDeveloperToolsRoute
  '/developer/users': typeof AuthenticatedDeveloperUsersRoute
  '/marker/appeals': typeof AuthenticatedMarkerAppealsRoute
  '/marker/password': typeof AuthenticatedMarkerPasswordRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/developer/': typeof AuthenticatedDeveloperIndexRoute
  '/marker/': typeof AuthenticatedMarkerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/developer-signin': typeof DeveloperSigninRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/marker-signin': typeof MarkerSigninRoute
  '/mii': typeof MiiRoute
  '/miu': typeof MiuRoute
  '/reset-password': typeof ResetPasswordRoute
  '/advisor': typeof AuthenticatedAdvisorRoute
  '/appeals': typeof AuthenticatedAppealsRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mail': typeof AuthenticatedMailRoute
  '/password': typeof AuthenticatedPasswordRoute
  '/admin/appeals': typeof AuthenticatedAdminAppealsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/blocks': typeof AuthenticatedAdminBlocksRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/cohorts': typeof AuthenticatedAdminCohortsRoute
  '/admin/directory': typeof AuthenticatedAdminDirectoryRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/markers': typeof AuthenticatedAdminMarkersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/developer/audit': typeof AuthenticatedDeveloperAuditRoute
  '/developer/email': typeof AuthenticatedDeveloperEmailRoute
  '/developer/emergency': typeof AuthenticatedDeveloperEmergencyRoute
  '/developer/flags': typeof AuthenticatedDeveloperFlagsRoute
  '/developer/health': typeof AuthenticatedDeveloperHealthRoute
  '/developer/integrity': typeof AuthenticatedDeveloperIntegrityRoute
  '/developer/permissions': typeof AuthenticatedDeveloperPermissionsRoute
  '/developer/search': typeof AuthenticatedDeveloperSearchRoute
  '/developer/security': typeof AuthenticatedDeveloperSecurityRoute
  '/developer/support': typeof AuthenticatedDeveloperSupportRoute
  '/developer/tools': typeof AuthenticatedDeveloperToolsRoute
  '/developer/users': typeof AuthenticatedDeveloperUsersRoute
  '/marker/appeals': typeof AuthenticatedMarkerAppealsRoute
  '/marker/password': typeof AuthenticatedMarkerPasswordRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/developer': typeof AuthenticatedDeveloperIndexRoute
  '/marker': typeof AuthenticatedMarkerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/developer-signin': typeof DeveloperSigninRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/marker-signin': typeof MarkerSigninRoute
  '/mii': typeof MiiRoute
  '/miu': typeof MiuRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/advisor': typeof AuthenticatedAdvisorRoute
  '/_authenticated/appeals': typeof AuthenticatedAppealsRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/developer': typeof AuthenticatedDeveloperRouteWithChildren
  '/_authenticated/mail': typeof AuthenticatedMailRoute
  '/_authenticated/marker': typeof AuthenticatedMarkerRouteWithChildren
  '/_authenticated/password': typeof AuthenticatedPasswordRoute
  '/_authenticated/admin/appeals': typeof AuthenticatedAdminAppealsRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/blocks': typeof AuthenticatedAdminBlocksRoute
  '/_authenticated/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/_authenticated/admin/cohorts': typeof AuthenticatedAdminCohortsRoute
  '/_authenticated/admin/directory': typeof AuthenticatedAdminDirectoryRoute
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/_authenticated/admin/markers': typeof AuthenticatedAdminMarkersRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/developer/audit': typeof AuthenticatedDeveloperAuditRoute
  '/_authenticated/developer/email': typeof AuthenticatedDeveloperEmailRoute
  '/_authenticated/developer/emergency': typeof AuthenticatedDeveloperEmergencyRoute
  '/_authenticated/developer/flags': typeof AuthenticatedDeveloperFlagsRoute
  '/_authenticated/developer/health': typeof AuthenticatedDeveloperHealthRoute
  '/_authenticated/developer/integrity': typeof AuthenticatedDeveloperIntegrityRoute
  '/_authenticated/developer/permissions': typeof AuthenticatedDeveloperPermissionsRoute
  '/_authenticated/developer/search': typeof AuthenticatedDeveloperSearchRoute
  '/_authenticated/developer/security': typeof AuthenticatedDeveloperSecurityRoute
  '/_authenticated/developer/support': typeof AuthenticatedDeveloperSupportRoute
  '/_authenticated/developer/tools': typeof AuthenticatedDeveloperToolsRoute
  '/_authenticated/developer/users': typeof AuthenticatedDeveloperUsersRoute
  '/_authenticated/marker/appeals': typeof AuthenticatedMarkerAppealsRoute
  '/_authenticated/marker/password': typeof AuthenticatedMarkerPasswordRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/developer/': typeof AuthenticatedDeveloperIndexRoute
  '/_authenticated/marker/': typeof AuthenticatedMarkerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/developer-signin'
    | '/forgot-password'
    | '/marker-signin'
    | '/mii'
    | '/miu'
    | '/reset-password'
    | '/admin'
    | '/advisor'
    | '/appeals'
    | '/classes'
    | '/dashboard'
    | '/developer'
    | '/mail'
    | '/marker'
    | '/password'
    | '/admin/appeals'
    | '/admin/attendance'
    | '/admin/blocks'
    | '/admin/classes'
    | '/admin/cohorts'
    | '/admin/directory'
    | '/admin/feedback'
    | '/admin/markers'
    | '/admin/reports'
    | '/admin/students'
    | '/developer/audit'
    | '/developer/email'
    | '/developer/emergency'
    | '/developer/flags'
    | '/developer/health'
    | '/developer/integrity'
    | '/developer/permissions'
    | '/developer/search'
    | '/developer/security'
    | '/developer/support'
    | '/developer/tools'
    | '/developer/users'
    | '/marker/appeals'
    | '/marker/password'
    | '/admin/'
    | '/developer/'
    | '/marker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/developer-signin'
    | '/forgot-password'
    | '/marker-signin'
    | '/mii'
    | '/miu'
    | '/reset-password'
    | '/advisor'
    | '/appeals'
    | '/classes'
    | '/dashboard'
    | '/mail'
    | '/password'
    | '/admin/appeals'
    | '/admin/attendance'
    | '/admin/blocks'
    | '/admin/classes'
    | '/admin/cohorts'
    | '/admin/directory'
    | '/admin/feedback'
    | '/admin/markers'
    | '/admin/reports'
    | '/admin/students'
    | '/developer/audit'
    | '/developer/email'
    | '/developer/emergency'
    | '/developer/flags'
    | '/developer/health'
    | '/developer/integrity'
    | '/developer/permissions'
    | '/developer/search'
    | '/developer/security'
    | '/developer/support'
    | '/developer/tools'
    | '/developer/users'
    | '/marker/appeals'
    | '/marker/password'
    | '/admin'
    | '/developer'
    | '/marker'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/developer-signin'
    | '/forgot-password'
    | '/marker-signin'
    | '/mii'
    | '/miu'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/advisor'
    | '/_authenticated/appeals'
    | '/_authenticated/classes'
    | '/_authenticated/dashboard'
    | '/_authenticated/developer'
    | '/_authenticated/mail'
    | '/_authenticated/marker'
    | '/_authenticated/password'
    | '/_authenticated/admin/appeals'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/blocks'
    | '/_authenticated/admin/classes'
    | '/_authenticated/admin/cohorts'
    | '/_authenticated/admin/directory'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/markers'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/students'
    | '/_authenticated/developer/audit'
    | '/_authenticated/developer/email'
    | '/_authenticated/developer/emergency'
    | '/_authenticated/developer/flags'
    | '/_authenticated/developer/health'
    | '/_authenticated/developer/integrity'
    | '/_authenticated/developer/permissions'
    | '/_authenticated/developer/search'
    | '/_authenticated/developer/security'
    | '/_authenticated/developer/support'
    | '/_authenticated/developer/tools'
    | '/_authenticated/developer/users'
    | '/_authenticated/marker/appeals'
    | '/_authenticated/marker/password'
    | '/_authenticated/admin/'
    | '/_authenticated/developer/'
    | '/_authenticated/marker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DeveloperSigninRoute: typeof DeveloperSigninRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MarkerSigninRoute: typeof MarkerSigninRoute
  MiiRoute: typeof MiiRoute
  MiuRoute: typeof MiuRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-signin': {
      id: '/developer-signin'
      path: '/developer-signin'
      fullPath: '/developer-signin'
      preLoaderRoute: typeof DeveloperSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marker-signin': {
      id: '/marker-signin'
      path: '/marker-signin'
      fullPath: '/marker-signin'
      preLoaderRoute: typeof MarkerSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mii': {
      id: '/mii'
      path: '/mii'
      fullPath: '/mii'
      preLoaderRoute: typeof MiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miu': {
      id: '/miu'
      path: '/miu'
      fullPath: '/miu'
      preLoaderRoute: typeof MiuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advisor': {
      id: '/_authenticated/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AuthenticatedAdvisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appeals': {
      id: '/_authenticated/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AuthenticatedAppealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer': {
      id: '/_authenticated/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mail': {
      id: '/_authenticated/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof AuthenticatedMailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marker': {
      id: '/_authenticated/marker'
      path: '/marker'
      fullPath: '/marker'
      preLoaderRoute: typeof AuthenticatedMarkerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/password': {
      id: '/_authenticated/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof AuthenticatedPasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/appeals': {
      id: '/_authenticated/admin/appeals'
      path: '/appeals'
      fullPath: '/admin/appeals'
      preLoaderRoute: typeof AuthenticatedAdminAppealsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blocks': {
      id: '/_authenticated/admin/blocks'
      path: '/blocks'
      fullPath: '/admin/blocks'
      preLoaderRoute: typeof AuthenticatedAdminBlocksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/classes': {
      id: '/_authenticated/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AuthenticatedAdminClassesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cohorts': {
      id: '/_authenticated/admin/cohorts'
      path: '/cohorts'
      fullPath: '/admin/cohorts'
      preLoaderRoute: typeof AuthenticatedAdminCohortsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/directory': {
      id: '/_authenticated/admin/directory'
      path: '/directory'
      fullPath: '/admin/directory'
      preLoaderRoute: typeof AuthenticatedAdminDirectoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/markers': {
      id: '/_authenticated/admin/markers'
      path: '/markers'
      fullPath: '/admin/markers'
      preLoaderRoute: typeof AuthenticatedAdminMarkersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/developer/': {
      id: '/_authenticated/developer/'
      path: '/'
      fullPath: '/developer/'
      preLoaderRoute: typeof AuthenticatedDeveloperIndexRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/audit': {
      id: '/_authenticated/developer/audit'
      path: '/audit'
      fullPath: '/developer/audit'
      preLoaderRoute: typeof AuthenticatedDeveloperAuditRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/email': {
      id: '/_authenticated/developer/email'
      path: '/email'
      fullPath: '/developer/email'
      preLoaderRoute: typeof AuthenticatedDeveloperEmailRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/emergency': {
      id: '/_authenticated/developer/emergency'
      path: '/emergency'
      fullPath: '/developer/emergency'
      preLoaderRoute: typeof AuthenticatedDeveloperEmergencyRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/flags': {
      id: '/_authenticated/developer/flags'
      path: '/flags'
      fullPath: '/developer/flags'
      preLoaderRoute: typeof AuthenticatedDeveloperFlagsRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/health': {
      id: '/_authenticated/developer/health'
      path: '/health'
      fullPath: '/developer/health'
      preLoaderRoute: typeof AuthenticatedDeveloperHealthRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/integrity': {
      id: '/_authenticated/developer/integrity'
      path: '/integrity'
      fullPath: '/developer/integrity'
      preLoaderRoute: typeof AuthenticatedDeveloperIntegrityRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/permissions': {
      id: '/_authenticated/developer/permissions'
      path: '/permissions'
      fullPath: '/developer/permissions'
      preLoaderRoute: typeof AuthenticatedDeveloperPermissionsRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/search': {
      id: '/_authenticated/developer/search'
      path: '/search'
      fullPath: '/developer/search'
      preLoaderRoute: typeof AuthenticatedDeveloperSearchRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/security': {
      id: '/_authenticated/developer/security'
      path: '/security'
      fullPath: '/developer/security'
      preLoaderRoute: typeof AuthenticatedDeveloperSecurityRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/support': {
      id: '/_authenticated/developer/support'
      path: '/support'
      fullPath: '/developer/support'
      preLoaderRoute: typeof AuthenticatedDeveloperSupportRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/tools': {
      id: '/_authenticated/developer/tools'
      path: '/tools'
      fullPath: '/developer/tools'
      preLoaderRoute: typeof AuthenticatedDeveloperToolsRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/users': {
      id: '/_authenticated/developer/users'
      path: '/users'
      fullPath: '/developer/users'
      preLoaderRoute: typeof AuthenticatedDeveloperUsersRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/marker/': {
      id: '/_authenticated/marker/'
      path: '/'
      fullPath: '/marker/'
      preLoaderRoute: typeof AuthenticatedMarkerIndexRouteImport
      parentRoute: typeof AuthenticatedMarkerRoute
    }
    '/_authenticated/marker/appeals': {
      id: '/_authenticated/marker/appeals'
      path: '/appeals'
      fullPath: '/marker/appeals'
      preLoaderRoute: typeof AuthenticatedMarkerAppealsRouteImport
      parentRoute: typeof AuthenticatedMarkerRoute
    }
    '/_authenticated/marker/password': {
      id: '/_authenticated/marker/password'
      path: '/password'
      fullPath: '/marker/password'
      preLoaderRoute: typeof AuthenticatedMarkerPasswordRouteImport
      parentRoute: typeof AuthenticatedMarkerRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAppealsRoute: typeof AuthenticatedAdminAppealsRoute
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminBlocksRoute: typeof AuthenticatedAdminBlocksRoute
  AuthenticatedAdminClassesRoute: typeof AuthenticatedAdminClassesRoute
  AuthenticatedAdminCohortsRoute: typeof AuthenticatedAdminCohortsRoute
  AuthenticatedAdminDirectoryRoute: typeof AuthenticatedAdminDirectoryRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
  AuthenticatedAdminMarkersRoute: typeof AuthenticatedAdminMarkersRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAppealsRoute: AuthenticatedAdminAppealsRoute,
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminBlocksRoute: AuthenticatedAdminBlocksRoute,
  AuthenticatedAdminClassesRoute: AuthenticatedAdminClassesRoute,
  AuthenticatedAdminCohortsRoute: AuthenticatedAdminCohortsRoute,
  AuthenticatedAdminDirectoryRoute: AuthenticatedAdminDirectoryRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
  AuthenticatedAdminMarkersRoute: AuthenticatedAdminMarkersRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDeveloperRouteChildren {
  AuthenticatedDeveloperAuditRoute: typeof AuthenticatedDeveloperAuditRoute
  AuthenticatedDeveloperEmailRoute: typeof AuthenticatedDeveloperEmailRoute
  AuthenticatedDeveloperEmergencyRoute: typeof AuthenticatedDeveloperEmergencyRoute
  AuthenticatedDeveloperFlagsRoute: typeof AuthenticatedDeveloperFlagsRoute
  AuthenticatedDeveloperHealthRoute: typeof AuthenticatedDeveloperHealthRoute
  AuthenticatedDeveloperIntegrityRoute: typeof AuthenticatedDeveloperIntegrityRoute
  AuthenticatedDeveloperPermissionsRoute: typeof AuthenticatedDeveloperPermissionsRoute
  AuthenticatedDeveloperSearchRoute: typeof AuthenticatedDeveloperSearchRoute
  AuthenticatedDeveloperSecurityRoute: typeof AuthenticatedDeveloperSecurityRoute
  AuthenticatedDeveloperSupportRoute: typeof AuthenticatedDeveloperSupportRoute
  AuthenticatedDeveloperToolsRoute: typeof AuthenticatedDeveloperToolsRoute
  AuthenticatedDeveloperUsersRoute: typeof AuthenticatedDeveloperUsersRoute
  AuthenticatedDeveloperIndexRoute: typeof AuthenticatedDeveloperIndexRoute
}

const AuthenticatedDeveloperRouteChildren: AuthenticatedDeveloperRouteChildren =
  {
    AuthenticatedDeveloperAuditRoute: AuthenticatedDeveloperAuditRoute,
    AuthenticatedDeveloperEmailRoute: AuthenticatedDeveloperEmailRoute,
    AuthenticatedDeveloperEmergencyRoute: AuthenticatedDeveloperEmergencyRoute,
    AuthenticatedDeveloperFlagsRoute: AuthenticatedDeveloperFlagsRoute,
    AuthenticatedDeveloperHealthRoute: AuthenticatedDeveloperHealthRoute,
    AuthenticatedDeveloperIntegrityRoute: AuthenticatedDeveloperIntegrityRoute,
    AuthenticatedDeveloperPermissionsRoute:
      AuthenticatedDeveloperPermissionsRoute,
    AuthenticatedDeveloperSearchRoute: AuthenticatedDeveloperSearchRoute,
    AuthenticatedDeveloperSecurityRoute: AuthenticatedDeveloperSecurityRoute,
    AuthenticatedDeveloperSupportRoute: AuthenticatedDeveloperSupportRoute,
    AuthenticatedDeveloperToolsRoute: AuthenticatedDeveloperToolsRoute,
    AuthenticatedDeveloperUsersRoute: AuthenticatedDeveloperUsersRoute,
    AuthenticatedDeveloperIndexRoute: AuthenticatedDeveloperIndexRoute,
  }

const AuthenticatedDeveloperRouteWithChildren =
  AuthenticatedDeveloperRoute._addFileChildren(
    AuthenticatedDeveloperRouteChildren,
  )

interface AuthenticatedMarkerRouteChildren {
  AuthenticatedMarkerAppealsRoute: typeof AuthenticatedMarkerAppealsRoute
  AuthenticatedMarkerPasswordRoute: typeof AuthenticatedMarkerPasswordRoute
  AuthenticatedMarkerIndexRoute: typeof AuthenticatedMarkerIndexRoute
}

const AuthenticatedMarkerRouteChildren: AuthenticatedMarkerRouteChildren = {
  AuthenticatedMarkerAppealsRoute: AuthenticatedMarkerAppealsRoute,
  AuthenticatedMarkerPasswordRoute: AuthenticatedMarkerPasswordRoute,
  AuthenticatedMarkerIndexRoute: AuthenticatedMarkerIndexRoute,
}

const AuthenticatedMarkerRouteWithChildren =
  AuthenticatedMarkerRoute._addFileChildren(AuthenticatedMarkerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAdvisorRoute: typeof AuthenticatedAdvisorRoute
  AuthenticatedAppealsRoute: typeof AuthenticatedAppealsRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeveloperRoute: typeof AuthenticatedDeveloperRouteWithChildren
  AuthenticatedMailRoute: typeof AuthenticatedMailRoute
  AuthenticatedMarkerRoute: typeof AuthenticatedMarkerRouteWithChildren
  AuthenticatedPasswordRoute: typeof AuthenticatedPasswordRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAdvisorRoute: AuthenticatedAdvisorRoute,
  AuthenticatedAppealsRoute: AuthenticatedAppealsRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeveloperRoute: AuthenticatedDeveloperRouteWithChildren,
  AuthenticatedMailRoute: AuthenticatedMailRoute,
  AuthenticatedMarkerRoute: AuthenticatedMarkerRouteWithChildren,
  AuthenticatedPasswordRoute: AuthenticatedPasswordRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DeveloperSigninRoute: DeveloperSigninRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MarkerSigninRoute: MarkerSigninRoute,
  MiiRoute: MiiRoute,
  MiuRoute: MiuRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
