ALTER TABLE public.blocks 
  ADD COLUMN IF NOT EXISTS cohort TEXT,
  ADD COLUMN IF NOT EXISTS points_per_session NUMERIC NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS standard_attendance_points NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS standard_attendance_percentage NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_attendance_points NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_attendance_percentage NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS weekly_required_points NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS enable_rounding BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS rounding_points NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS friday_pm_optional BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS saturday_optional BOOLEAN NOT NULL DEFAULT false;
